services:
  app:
    build:
        context: .
        dockerfile: Dockerfile.dev
    ports:
      - '${APP_PORT:-3000}:3000'
    command: sh -c "npm install && npm run start:dev"
    env_file:
      - .env
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - PORT=${APP_PORT:-3000}
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-postgres}
    volumes:
        - db-data:/var/lib/postgresql/data
volumes:
    db-data:
